repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-added-large-files
      exclude: ^package-lock.json$
    - id: pretty-format-json
      args: ["--autofix", "--no-sort-keys"]
    - id: detect-private-key
    - id: name-tests-test
    - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
        "--rcfile=./server/.pylintrc"
        ]
      - id: poetry-check
        name: poetry-check
        description: run poetry check to validate config
        entry: bash -c "cd server && exec poetry check"
        language: system
        pass_filenames: false
        verbose: true
      - id: poetry-lock
        name: poetry-lock
        description: run poetry lock to update lock file
        entry: bash -c "cd server && exec poetry lock"
        language: system
        pass_filenames: false
        verbose: true
      - id: poetry-export
        name: poetry-export
        description: run poetry export to sync lock file with requirements.txt
        entry: bash -c "cd server && exec sh write_requirements.sh"
        language: system
        pass_filenames: false
        always_run: true
